name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v
      #- uses: getsentry/action-git-diff-suggestions@main
      #  with:
      #    message: 'Testing diff'
      #- uses: actions/checkout@v2
      #- uses: actions/setup-java@v2
      #  with:
      #    distribution: 'adopt' # See 'Supported distributions' for available options
      #    java-version: '11'
      #- run: javac *.java
      #- run: ls -la
      #- run: java -cp . HelloWorld
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: {{ secrets.GITHUB_TOKEN }}
          # Comment to post on an individual's first issue
          issue-message: "This is your first issue"
          # Comment to post on an individual's first pull request
          pr-message: "This your first pull request"    

